// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         ref: "ref"
 *     }
 */
export interface CancelBookingApiV1BookingsRefDeleteRequest {
    ref: string;
}
