// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         shop_name: "shop_name",
 *         service: "service",
 *         date: "date",
 *         time: "time"
 *     }
 */
export interface CreateBookingRequest {
    shop_name: string;
    service: string;
    date: string;
    time: string;
    phone?: string;
    customer_name?: string;
    car_info?: string;
    bundle_id?: string | null;
}
