// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         phone: "phone"
 *     }
 */
export interface GetBookingsByPhoneApiV1BookingsByPhonePhoneGetRequest {
    phone: string;
}
