// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         ref: "ref",
 *         new_date: "new_date",
 *         new_time: "new_time"
 *     }
 */
export interface RescheduleRequest {
    ref: string;
    new_date: string;
    new_time: string;
}
