// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name",
 *         phone: "phone",
 *         password: "password"
 *     }
 */
export interface ClientRegisterRequest {
    name: string;
    phone: string;
    password: string;
    car_make?: string;
    car_model?: string;
    car_plate?: string;
}
