// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetNearbyShopsApiV1ShopsNearbyGetRequest {
    latitude?: number | null;
    longitude?: number | null;
    address?: string | null;
    date?: string | null;
    service?: string | null;
}
