// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         shop_id: "shop_id"
 *     }
 */
export interface GetShopApiV1ShopsShopIdGetRequest {
    shop_id: string;
}
