// This file was auto-generated by Fern from our API Definition.

import { AuthClient } from "./api/resources/auth/client/Client.js";
import { BookingsClient } from "./api/resources/bookings/client/Client.js";
import { ClientAuthClient } from "./api/resources/clientAuth/client/Client.js";
import { ClientProfileClient } from "./api/resources/clientProfile/client/Client.js";
import { MerchantsClient } from "./api/resources/merchants/client/Client.js";
import { ShopsClient } from "./api/resources/shops/client/Client.js";
import { UsersClient } from "./api/resources/users/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "./BaseClient.js";
import { mergeHeaders } from "./core/headers.js";
import * as core from "./core/index.js";
import { handleNonStatusCodeError } from "./errors/handleNonStatusCodeError.js";
import * as errors from "./errors/index.js";

export declare namespace WashlySDKClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class WashlySDKClient {
    protected readonly _options: NormalizedClientOptions<WashlySDKClient.Options>;
    protected _auth: AuthClient | undefined;
    protected _bookings: BookingsClient | undefined;
    protected _clientAuth: ClientAuthClient | undefined;
    protected _clientProfile: ClientProfileClient | undefined;
    protected _merchants: MerchantsClient | undefined;
    protected _shops: ShopsClient | undefined;
    protected _users: UsersClient | undefined;

    constructor(options: WashlySDKClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    public get auth(): AuthClient {
        return (this._auth ??= new AuthClient(this._options));
    }

    public get bookings(): BookingsClient {
        return (this._bookings ??= new BookingsClient(this._options));
    }

    public get clientAuth(): ClientAuthClient {
        return (this._clientAuth ??= new ClientAuthClient(this._options));
    }

    public get clientProfile(): ClientProfileClient {
        return (this._clientProfile ??= new ClientProfileClient(this._options));
    }

    public get merchants(): MerchantsClient {
        return (this._merchants ??= new MerchantsClient(this._options));
    }

    public get shops(): ShopsClient {
        return (this._shops ??= new ShopsClient(this._options));
    }

    public get users(): UsersClient {
        return (this._users ??= new UsersClient(this._options));
    }

    /**
     * @param {WashlySDKClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.healthHealthGet()
     */
    public healthHealthGet(requestOptions?: WashlySDKClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__healthHealthGet(requestOptions));
    }

    private async __healthHealthGet(
        requestOptions?: WashlySDKClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "health",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.WashlySDKError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/health");
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
            },
            requestOptions,
        );
    }
}
