// This file was auto-generated by Fern from our API Definition.

import type * as WashlySDK from "../index.js";

export interface AvailabilityOutput {
    weekly_hours?: WashlySDK.WeeklyHours | undefined;
    blackout_dates?: string[] | undefined;
}
