// This file was auto-generated by Fern from our API Definition.

export interface Bundle {
    id: string;
    name: string;
    description?: string | undefined;
    price: number;
    duration_minutes: number;
    active?: boolean | undefined;
}
