// This file was auto-generated by Fern from our API Definition.

export interface CarResponse {
    car_id: string;
    make: string;
    model: string;
    plate: string;
    is_primary?: boolean | undefined;
}
