// This file was auto-generated by Fern from our API Definition.

export interface ClientLoginResponse {
    authenticated: boolean;
    user_id?: string | undefined;
    name?: string | undefined;
    session_token?: (string | null) | undefined;
}
