// This file was auto-generated by Fern from our API Definition.

export interface ClientSessionResponse {
    authenticated: boolean;
    user_id?: string | undefined;
    name?: string | undefined;
}
