// This file was auto-generated by Fern from our API Definition.

import type * as WashlySDK from "../index.js";

export interface ClientProfileResponse {
    user_id: string;
    name: string;
    phone: string;
    tier?: string | undefined;
    cars?: WashlySDK.CarResponse[] | undefined;
    service_history?: string[] | undefined;
}
