// This file was auto-generated by Fern from our API Definition.

import type * as WashlySDK from "../index.js";

export interface HttpValidationError {
    detail?: WashlySDK.ValidationError[] | undefined;
}
