// This file was auto-generated by Fern from our API Definition.

export interface LoginResponse {
    authenticated: boolean;
    name?: string | undefined;
    shop_id?: string | undefined;
    session_token?: (string | null) | undefined;
}
