// This file was auto-generated by Fern from our API Definition.

import type * as WashlySDK from "../index.js";

export interface PricingResponse {
    services_pricing?: WashlySDK.ServicePricing[] | undefined;
    bundles?: WashlySDK.Bundle[] | undefined;
    updated_at?: (string | null) | undefined;
}
