// This file was auto-generated by Fern from our API Definition.

export interface ServicePricing {
    id: string;
    name: string;
    s?: string | undefined;
    m?: string | undefined;
    l?: string | undefined;
    currency?: string | undefined;
}
