// This file was auto-generated by Fern from our API Definition.

export interface ServicePricingInput {
    id?: (string | null) | undefined;
    name: string;
    s?: string | undefined;
    m?: string | undefined;
    l?: string | undefined;
    currency?: string | undefined;
}
