// This file was auto-generated by Fern from our API Definition.

import type * as WashlySDK from "../index.js";

export interface WeeklyHours {
    mon?: (WashlySDK.DayHours | null) | undefined;
    tue?: (WashlySDK.DayHours | null) | undefined;
    wed?: (WashlySDK.DayHours | null) | undefined;
    thu?: (WashlySDK.DayHours | null) | undefined;
    fri?: (WashlySDK.DayHours | null) | undefined;
    sat?: (WashlySDK.DayHours | null) | undefined;
    sun?: (WashlySDK.DayHours | null) | undefined;
}
