// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         make: "make",
 *         model: "model",
 *         plate: "plate"
 *     }
 */
export interface AddCarRequest {
    make: string;
    model: string;
    plate: string;
    set_primary?: boolean;
}
