// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         car_id: "car_id"
 *     }
 */
export interface RemoveCarApiV1ClientMeCarsCarIdDeleteRequest {
    car_id: string;
}
