// This file was auto-generated by Fern from our API Definition.

import type * as WashlySDK from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface AvailabilityInput {
    weekly_hours?: WashlySDK.WeeklyHours;
    blackout_dates?: string[];
}
