// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name",
 *         price: 1.1,
 *         duration_minutes: 1
 *     }
 */
export interface BundleCreate {
    name: string;
    description?: string;
    price: number;
    duration_minutes: number;
}
