// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         bundle_id: "bundle_id"
 *     }
 */
export interface BundleUpdate {
    bundle_id: string;
    name?: string | null;
    description?: string | null;
    price?: number | null;
    duration_minutes?: number | null;
    active?: boolean | null;
}
