// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         bundle_id: "bundle_id"
 *     }
 */
export interface DeleteBundleApiV1MerchantsMeShopBundlesBundleIdDeleteRequest {
    bundle_id: string;
}
