// This file was auto-generated by Fern from our API Definition.

import type * as WashlySDK from "../../../../index.js";

/**
 * @example
 *     {
 *         services_pricing: [{
 *                 name: "name"
 *             }]
 *     }
 */
export interface PricingUpdate {
    services_pricing: WashlySDK.ServicePricingInput[];
}
