// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ShopProfileUpdate {
    name?: string | null;
    location?: string | null;
    district?: string | null;
    phone?: string | null;
    specialty?: string | null;
}
