// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as WashlySDK from "../../../index.js";

export declare namespace MerchantsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class MerchantsClient {
    protected readonly _options: NormalizedClientOptions<MerchantsClient.Options>;

    constructor(options: MerchantsClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {MerchantsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WashlySDK.UnprocessableEntityError}
     *
     * @example
     *     await client.merchants.getPricing()
     */
    public getPricing(
        requestOptions?: MerchantsClient.RequestOptions,
    ): core.HttpResponsePromise<WashlySDK.PricingResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getPricing(requestOptions));
    }

    private async __getPricing(
        requestOptions?: MerchantsClient.RequestOptions,
    ): Promise<core.WithRawResponse<WashlySDK.PricingResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "api/v1/merchants/me/shop/pricing",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as WashlySDK.PricingResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new WashlySDK.UnprocessableEntityError(
                        _response.error.body as WashlySDK.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WashlySDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/merchants/me/shop/pricing",
        );
    }

    /**
     * @param {WashlySDK.PricingUpdate} request
     * @param {MerchantsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WashlySDK.UnprocessableEntityError}
     *
     * @example
     *     await client.merchants.patchPricing({
     *         services_pricing: [{
     *                 name: "name"
     *             }]
     *     })
     */
    public patchPricing(
        request: WashlySDK.PricingUpdate,
        requestOptions?: MerchantsClient.RequestOptions,
    ): core.HttpResponsePromise<WashlySDK.PricingResponse> {
        return core.HttpResponsePromise.fromPromise(this.__patchPricing(request, requestOptions));
    }

    private async __patchPricing(
        request: WashlySDK.PricingUpdate,
        requestOptions?: MerchantsClient.RequestOptions,
    ): Promise<core.WithRawResponse<WashlySDK.PricingResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "api/v1/merchants/me/shop/pricing",
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as WashlySDK.PricingResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new WashlySDK.UnprocessableEntityError(
                        _response.error.body as WashlySDK.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WashlySDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/api/v1/merchants/me/shop/pricing",
        );
    }

    /**
     * @param {WashlySDK.BundleCreate} request
     * @param {MerchantsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WashlySDK.UnprocessableEntityError}
     *
     * @example
     *     await client.merchants.createBundle({
     *         name: "name",
     *         price: 1.1,
     *         duration_minutes: 1
     *     })
     */
    public createBundle(
        request: WashlySDK.BundleCreate,
        requestOptions?: MerchantsClient.RequestOptions,
    ): core.HttpResponsePromise<WashlySDK.Bundle> {
        return core.HttpResponsePromise.fromPromise(this.__createBundle(request, requestOptions));
    }

    private async __createBundle(
        request: WashlySDK.BundleCreate,
        requestOptions?: MerchantsClient.RequestOptions,
    ): Promise<core.WithRawResponse<WashlySDK.Bundle>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "api/v1/merchants/me/shop/bundles",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as WashlySDK.Bundle, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new WashlySDK.UnprocessableEntityError(
                        _response.error.body as WashlySDK.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WashlySDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/merchants/me/shop/bundles",
        );
    }

    /**
     * @param {WashlySDK.DeleteBundleApiV1MerchantsMeShopBundlesBundleIdDeleteRequest} request
     * @param {MerchantsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WashlySDK.UnprocessableEntityError}
     *
     * @example
     *     await client.merchants.deleteBundle({
     *         bundle_id: "bundle_id"
     *     })
     */
    public deleteBundle(
        request: WashlySDK.DeleteBundleApiV1MerchantsMeShopBundlesBundleIdDeleteRequest,
        requestOptions?: MerchantsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__deleteBundle(request, requestOptions));
    }

    private async __deleteBundle(
        request: WashlySDK.DeleteBundleApiV1MerchantsMeShopBundlesBundleIdDeleteRequest,
        requestOptions?: MerchantsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { bundle_id: bundleId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api/v1/merchants/me/shop/bundles/${core.url.encodePathParam(bundleId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new WashlySDK.UnprocessableEntityError(
                        _response.error.body as WashlySDK.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WashlySDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/api/v1/merchants/me/shop/bundles/{bundle_id}",
        );
    }

    /**
     * @param {WashlySDK.BundleUpdate} request
     * @param {MerchantsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WashlySDK.UnprocessableEntityError}
     *
     * @example
     *     await client.merchants.patchBundle({
     *         bundle_id: "bundle_id"
     *     })
     */
    public patchBundle(
        request: WashlySDK.BundleUpdate,
        requestOptions?: MerchantsClient.RequestOptions,
    ): core.HttpResponsePromise<WashlySDK.Bundle> {
        return core.HttpResponsePromise.fromPromise(this.__patchBundle(request, requestOptions));
    }

    private async __patchBundle(
        request: WashlySDK.BundleUpdate,
        requestOptions?: MerchantsClient.RequestOptions,
    ): Promise<core.WithRawResponse<WashlySDK.Bundle>> {
        const { bundle_id: bundleId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `api/v1/merchants/me/shop/bundles/${core.url.encodePathParam(bundleId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as WashlySDK.Bundle, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new WashlySDK.UnprocessableEntityError(
                        _response.error.body as WashlySDK.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WashlySDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/api/v1/merchants/me/shop/bundles/{bundle_id}",
        );
    }

    /**
     * @param {MerchantsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WashlySDK.UnprocessableEntityError}
     *
     * @example
     *     await client.merchants.getAvailability()
     */
    public getAvailability(
        requestOptions?: MerchantsClient.RequestOptions,
    ): core.HttpResponsePromise<WashlySDK.AvailabilityOutput> {
        return core.HttpResponsePromise.fromPromise(this.__getAvailability(requestOptions));
    }

    private async __getAvailability(
        requestOptions?: MerchantsClient.RequestOptions,
    ): Promise<core.WithRawResponse<WashlySDK.AvailabilityOutput>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "api/v1/merchants/me/shop/availability",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as WashlySDK.AvailabilityOutput, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new WashlySDK.UnprocessableEntityError(
                        _response.error.body as WashlySDK.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WashlySDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/merchants/me/shop/availability",
        );
    }

    /**
     * @param {WashlySDK.AvailabilityInput} request
     * @param {MerchantsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WashlySDK.UnprocessableEntityError}
     *
     * @example
     *     await client.merchants.putAvailability()
     */
    public putAvailability(
        request: WashlySDK.AvailabilityInput = {},
        requestOptions?: MerchantsClient.RequestOptions,
    ): core.HttpResponsePromise<WashlySDK.AvailabilityOutput> {
        return core.HttpResponsePromise.fromPromise(this.__putAvailability(request, requestOptions));
    }

    private async __putAvailability(
        request: WashlySDK.AvailabilityInput = {},
        requestOptions?: MerchantsClient.RequestOptions,
    ): Promise<core.WithRawResponse<WashlySDK.AvailabilityOutput>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "api/v1/merchants/me/shop/availability",
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as WashlySDK.AvailabilityOutput, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new WashlySDK.UnprocessableEntityError(
                        _response.error.body as WashlySDK.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WashlySDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/api/v1/merchants/me/shop/availability",
        );
    }

    /**
     * @param {MerchantsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WashlySDK.UnprocessableEntityError}
     *
     * @example
     *     await client.merchants.getShopProfile()
     */
    public getShopProfile(
        requestOptions?: MerchantsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__getShopProfile(requestOptions));
    }

    private async __getShopProfile(
        requestOptions?: MerchantsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "api/v1/merchants/me/shop",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new WashlySDK.UnprocessableEntityError(
                        _response.error.body as WashlySDK.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WashlySDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/merchants/me/shop");
    }

    /**
     * @param {WashlySDK.ShopProfileUpdate} request
     * @param {MerchantsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WashlySDK.UnprocessableEntityError}
     *
     * @example
     *     await client.merchants.patchShopProfile()
     */
    public patchShopProfile(
        request: WashlySDK.ShopProfileUpdate = {},
        requestOptions?: MerchantsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__patchShopProfile(request, requestOptions));
    }

    private async __patchShopProfile(
        request: WashlySDK.ShopProfileUpdate = {},
        requestOptions?: MerchantsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "api/v1/merchants/me/shop",
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new WashlySDK.UnprocessableEntityError(
                        _response.error.body as WashlySDK.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WashlySDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/api/v1/merchants/me/shop");
    }

    /**
     * @param {MerchantsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WashlySDK.UnprocessableEntityError}
     *
     * @example
     *     await client.merchants.getShopBookings()
     */
    public getShopBookings(
        requestOptions?: MerchantsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>[]> {
        return core.HttpResponsePromise.fromPromise(this.__getShopBookings(requestOptions));
    }

    private async __getShopBookings(
        requestOptions?: MerchantsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>[]>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "api/v1/merchants/me/shop/bookings",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new WashlySDK.UnprocessableEntityError(
                        _response.error.body as WashlySDK.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WashlySDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/merchants/me/shop/bookings",
        );
    }
}
