// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         phone: "phone",
 *         password: "password"
 *     }
 */
export interface LoginRequest {
    phone: string;
    password: string;
}
